#!/bin/bash

# Update the main repository
git pull --rebase

# Update all submodules
git submodule update --init --recursive
git submodule foreach 'git checkout main || git checkout master; git pull --rebase'
git add .
git commit -m "Update plugins to latest versions" || echo "No plugin updates"
git push
